### ISSUE TITLE
add comments to parabola.py

### ISSUE THREAD

**Issue by apoleon33** [UpsilonNumworks/Upsilon#105]
**Is your feature request related to a problem? Please describe.**
actually at the moment every auto-installed python scripts have a pretty clear docstring, so a newcommer know a little bit how it work, except for parabola.py

**Describe the solution you'd like**
I don't think its pretty hard to do that, if I knew (and knew how tf parabola.py work) how to modify i would have done it by myself

**Additional context**
:)

**Comment by Lauryy06** [comment]
We have removed auto-installed scripts.

**Comment by RedGl0w** [comment]
> and knew how tf parabola.py work

Indeed, that's not so hard : it's just an application of the 2nd law of Newton only with weight for the x, y, vx, vy part. For t_max, i think it's just an function which will find the latest time before the impact (y=0). These results could be pretty easily found.

**Comment by apoleon33** [comment]
> We have removed auto-installed scripts.

thats at this moment that you know you do not have checked upsilon for a long time
