### ISSUE TITLE
Do not close the python toolbox when module function prefix is selected

### ISSUE THREAD

**Issue by Syycorax** [UpsilonNumworks/Upsilon#109]
I would like the toolbox not to be closed when I select the "module function prefix" option like [here](https://imgur.com/a/QvqC78q) with the math module so that I'm not forced to re-open the toolbox to write a function.

**Comment by Lauryy06** [comment]
Thanks for the issue. I think it's easy to code that the toolbox must stay open if you press something like shift button at same time, so I will probably do it.

**Comment by Lauryy06** [comment]
I fix it in e575ffc7ce3ce0b5c3091546cf0eab2d73ecec07.
