### ISSUE TITLE
setting value not stored in the Function app

### ISSUE THREAD

**Issue by Overengined** [UpsilonNumworks/Upsilon#117]
**Describe the bug**
The "derived number of f in a" setting is reseted when one leaves the Function app.

**To Reproduce**
1. create a derivable function in the Function app
2. press the OK button on the graphic representation of said function and turn on "derived number of f in a"
3. leave the app
4. go back to the app, and then go to the graph tab, the derived number isn't there anymore, and you'll be able to see, if you go back in the above-mentionned menu, that the "derived number of f in a" has been reseted to it's default value (off).

**Expected behavior**
The setting should keep the value the user gave it when leaving the app. So that there is non need to constantly go back to the setting menu.

**Device (please complete the following information):**
 n011 running Omega 1.23

**Comment by Lauryy06** [comment]
Thanks for the issue. I think it's not really a bug, but the idea is nice and it's easy to fix.

**Comment by Lauryy06** [comment]
I fixed it (f591816122e19dae3abc5675c30e8e9f3b6a9eea)
