### ISSUE TITLE
Equations with complex numbers make Upsilon crash

### ISSUE THREAD

**Issue by Dreaming-Codes** [UpsilonNumworks/Upsilon#123]
**Describe the bug**
Equations with complex numbers make Upsilon crash throwing BUSFAULT

**To Reproduce**
1. Go to 'Equations'
2. Click on 'Add equation'
3. Input '(4i+√(-36))/(2) = 0
4. Click on 'Solve the equation'
5. See the error

**Expected behavior**
It should handle the error and say that it is not possible to resolve the equation.

**Screenshots**
![PXL_20220113_124346758.jpg](https://user-images.githubusercontent.com/10401566/149324408-27c25592-936d-4afd-858f-c2d22d085a26.jpg)
![PXL_20220113_124355139.jpg](https://user-images.githubusercontent.com/10401566/149324450-d2104dd2-cc57-4916-a7a3-9c24f71575b9.jpg)

**Device (please complete the following information):**
 - The device on which you're running Upsilon n0110
 - Upsilon Version: 1.22.1

**Comment by Lauryy06** [comment]
Thanks for the issue, I manage to reproduce the bug, I will try to fix it soon.

**Comment by Lauryy06** [comment]
I think it's fixed now (cbbe7ef6accd35db4ac493a9862a49f53549e110), thank you for the issue and the precise details.
