### ISSUE TITLE
All Python scrips where crippled

### ISSUE THREAD

**Issue by L0rdS474n** [UpsilonNumworks/Upsilon#139]
**Describe the bug**
Not sure if I did something wrong or it's in the Upsilon update.
I got my Numworks today and it had 15.5 so I just updated with Upsilon and noted that every Python script was damaged.
Almost all had missing characters in the beginning of the file. Mandelbrot missed the comment # and the other files missed fr in from math import *

Other than that it seems to work as it should.

**To Reproduce**
Use a new Numworks Calculator with 15.5 OS
Just go in and upgrade the calculator to Upsilon and all Python scripts are broken.

**Expected behavior**
All Python scripts should work after the upgrade if you choose to remove the scripts etc.

**Screenshots**

**Device (please complete the following information):**
 - The device on which you're running Upsilon (computer, n0110, n0100, etc...) n0110
 - Upsilon Version: [go to settings > about > Upsilon Version and type the version here] 1.0.0.0-dev
 - Upsilon commit: [settings > about > click one time on epsilon version] 1a546e0

**Comment by Lauryy06** [comment]
I think that's "normal". Now we store the cursor location in the python file, and it takes 2 bytes at the beginning of each file, so all your pre-existing files were truncated by two characters.
So this is not supposed to happen again, but sorry for the inconvenience.

**Comment by L0rdS474n** [comment]
Second time it killed all scripts so now I don't have the nice mandelbrot anymore :(
But I don't have the crippled original at least.

**Comment by Yaya-Cout** [comment]
This bug will be fixed by this pull request, but it isn't merged at this time : M4xi1m3/Numworks.js#4

**Comment by L0rdS474n** [comment]
Nice work, looking forward to this new release.
Will it be a normal update from the website?

**Comment by Yaya-Cout** [comment]
Yes
