### ISSUE TITLE
Effacer se fait sans filet

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#150]
Problème rencontré : 
Un unique appui sur la touche "efface" ("CLEAR") supprime une fonction ou une équation. Or ces fonctions ou équations ont parfois été longues à définir.

Solution proposée  : 
Ajouter une securité à l'effacement.
Vous trouverez la meilleure solution.  On peut imaginer :
- soit annuler l'effacement si on appuie immédiatement sur la touche "retour" (touche ronde a droite de la touche "OK") apres un appui sur la touche "efface"
- soit pouvoir redéfinir la fonction/équation par appel à une mémoire dans la liste des fonctions proposées
- soit demander confirmation (message à l'écran) par un 2e appui sur la touche "efface"

**Comment by Lauryy06** [comment]
Je pense qu'ajouter une confirmation serait trop lourd pour l'utilisateur, mais garder le résultat en mémoire un certains temps pour le restaurer via (par exemple) Shift+Retour semble possible, bien qu'il faille l'ajouter manuellement dand chacunes des applications.

**Comment by fmOOmf** [comment]
Bonjour.
2 propositions pour alimenter la recherche d'une solution facile et intuitive pour l'utilisateur.

1-  "clear" efface l'affichage, sans effacer la définition de la fonction ou équation
Un shift retour  rétablirait l'affichage de la fonction (toujours en mémoire). Toute autre touche effacerait effectivement la définition de la fonction avant de s'exécuter.

2- effacer une fonction ou equation se fait par un "shift clear". Étant plus  difficile à faire par inadvertance qu'un Clear, aucun filet de sécurité ne serait  à implémenter.
Dans les menus des Options des fonctions, (type de courbe, activer/desactiver) on peut rajouter "Supprimer (shift clear)" pour être sûr que l'utilisateur apprenne comment faire.

**Comment by Yaya-Cout** [comment]
Je pense que le Shift+clear n'est pas une bonne idée, car il est déjà utilisé pour tout effacer.

**Comment by devdl11** [comment]
Tiens tiens tiens, une autre sécurité ! Maybe je vais m'y pencher dessus x) (si vous pouvez le faire faites le n'hésitez pas ^^)

**Comment by fmOOmf** [comment]
Effectivement. Donc exit pour le point 2.

**Comment by Lauryy06** [comment]
Que pensez-vous de f3d632c462c7342742eec6ca6b85f4b3248d5227 ? J'ai ajouté un moyen de récupérer le dernier calcul effacé en appuyant sur Shift + Back.
Je pense que c'est une bonne base pour ajouter cette fonctionnalité aux application Equation, Fonctions, etc...

**Comment by fmOOmf** [comment]
👍
Cela va être magique !

**Comment by Lauryy06** [comment]
C'est fait, Shift + Back permet de remettre le dernier fichier effacer (sauf si un autre a été créé entre temps), dans les apps Fonctions, Suites, Equations et Python ! (voir af5f9ea578694a1500b4a888f0c138c1c0273c49)

**Comment by fmOOmf** [comment]
Bravo !
😊
