### ISSUE TITLE
Redefinir les couleurs des courbes

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#151]
Probleme rencontré : 
Lorsqu'on efface une courbe et qu'on en définit une nouvelle, la couleur change. On se retrouve rapidement avec des couleurs difficiles à percevoir, d'autant plus quand plusieurs courbes ou tangentes sont  affichées.

Solution proposée:
Pouvoir modifier la couleur des courbes

**Comment by Yaya-Cout** [comment]
Do you want something like numworks#1741 ?

**Comment by AlexandreArduino** [comment]
I started to make it do you want to do it @Yaya-Cout ? or I continue ? :thinking:

**Comment by Yaya-Cout** [comment]
No, you can do it

**Comment by AlexandreArduino** [comment]
okay :p

**Comment by AlexandreArduino** [comment]
> 

you can see the pull request #153 and tell me what you think if you want (there is a video to demonstrate the new feature)
