### ISSUE TITLE
3 formes polynôme du second degré

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#152]
0Amélioration proposée : 
(Application calcul) : quand écrit un polynôme du 2nd degré, proposer les 3 choix suivants dans les résultats complementaires : 
" forme 1:  générale" 
" forme 2 : factorisée" 
" forme 3 : canonique"

Sélectionner l'une des forme afficherait le résultat, à savoir :
" forme 1:  affichage de  ax^2+bx+c
" forme 2 : affichage de a(x-x1)(x-x2) ou a(x-x0)^2 ou "pas de racines"
" forme 3 : affichage de  a(x-alpha)^2 +beta

Avec les valeurs de a; b, c, x0, x1, alpha et bêta calculées bien sûr.

Grande valeur ajoutée pour les élèves qui peuvent vérifier que leurs calculs sont justes.

**Comment by Yaya-Cout** [comment]
Do you want something like NumWorks#1741 ?

**Comment by Lauryy06** [comment]
C'est déjà fait !

**Comment by fmOOmf** [comment]
Super. A clôturer alors.
