### ISSUE TITLE
[ simulateur ]

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#154]
A part un fond d'écran, rien ne s'affiche quand je clique sur "simulateur depuis le site web de Upsilon.

Y a-t-il des contraintes sur l'explorateur ? (Actuellement windows 10 et Microsoft Edge 97.0.1072.55 (64 bits)

**Comment by Yaya-Cout** [comment]
Version française
C'est normal que le simulateur ne marche pas : on est en train de le coder

---
English version
It's normal that the simulator doesn't work : we are coding it

**Comment by Lauryy06** [comment]
D'ailleurs cette issue n'est pas liée à Upsilon mais au [site web](https://github.com/lolocomotive/Upsilon-website). Je vous invite donc à la réouvrir là-bas.

**Comment by fmOOmf** [comment]
Merci pour ces reponses. Un message du type "bientôt disponible " permettra à tous d'être prévenus que la sympathique équipe Upsilon est à l'oeuvre, et que nous devons être patients.
