### ISSUE TITLE
[x, n, t] 

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#157]
Proposition : 
Des appuis successifs sur la touche "x,n,t" permettent d'écrire  x puis n puis t puis theta (lettre greque) comme pour le firmware epsilon 17.2.

- Conserver les choix intelligents du premier affichage (mais permettre de cycler) : 
x pour les fonctions "classiques"
n pour les suites
t pour les fonctions paramètriques
theta pour les polaires 
- La fleche droite force la sélection, ce qui permet d'écrire "nxt" .

**Comment by Lauryy06** [comment]
Est-ce réellement utile ?

**Comment by fmOOmf** [comment]
Pour moi oui, ce sont tous ces petits plus qui contribuent à la fluidité et font in fine le succès de  Upsilon. Et l'accès au theta n'est actuellement pas évident ...

Mais nous ne faisons que suggérer, à vous de disposer. Bon courage à toute l'équipe.

**Comment by AlexandreArduino** [comment]
> Est-ce réellement utile ?

perso je trouve que oui car au vue de la disposition de la touche sur le "clavier" on s'attend en appuyant plusieurs fois dessus à pouvoir sélectionner la lettre que l'on veut :thinking: tout en gardant la sélection de base en fonction de l'app ou du contexte

**Comment by Lauryy06** [comment]
Fixed in 51a5f699c3dbe75e0644b005f2047bc2bd316860
