### ISSUE TITLE
Is it possible to avoid to reset the calculator after uploading Upsilon ?

### ISSUE THREAD

**Issue by AlexandreArduino** [UpsilonNumworks/Upsilon#161]
When you install Upsilon manually you need to reset the calculator to use it but is it possible to remove this reset ? I know it is because Omega and Epsilon have not this problem :thinking:

**Comment by Lauryy06** [comment]
In my memory the last version of omega also has this problem, but I don't know what it is due to...

**Comment by AlexandreArduino** [comment]
i will try to find the problem :thinking:

**Comment by Lauryy06** [comment]
Good luck

**Comment by Yaya-Cout** [comment]
I think it is a bug in the USB protection : it was working before

**Comment by AlexandreArduino** [comment]
interesting i will try to resolve that

**Comment by Yaya-Cout** [comment]
Is it still valid ?
