### ISSUE TITLE
La calculatrice ne marche pas avec certains calculs

### ISSUE THREAD

**Issue by Lolothepro** [UpsilonNumworks/Upsilon#162]
1. Aller dans le menu
2. Calculer (x-1)(x+3)
3. Appuyer sur les trois petit point
4. Upsilon crash

n110 
Upsilon 1.0.0-dev

**Comment by Lauryy06** [comment]
Sur quel commit est basé votre version ? (Paramètres > A propos > Version d'Epsilon >  Double clic)

 Normalement ce bug a déjà été corrigé, le calcul fonctionne parfaitement sur mon appareil.

**Comment by Lolothepro** [comment]
03.43

**Comment by Lolothepro** [comment]
70c3889

**Comment by Lauryy06** [comment]
C'est étrange, ce commit date d'après mon fix... Combien de fois ce bug vous est-il arrivé ?

**Comment by lolocomotive** [comment]
> 70c3889

Oh non on voit mes messages de commit dégueulasse

**Comment by Lolothepro** [comment]
tout le temps en fait, a chaque fois que je met le calcul, je vais voir en mettant a jour Upsilon

**Comment by Lolothepro** [comment]
Cela a l'air d'être fixer dans la branche de développement

**Comment by fmOOmf** [comment]
A propos, j'attends précisément que la 1.0 officielle sorte avant de l'installer  pour eviter ce ce de  désagréments. Y a-t-il une date visée plur la 1.0 tant attendue ?

**Comment by fmOOmf** [comment]
A clôturer ? Dommage que cet issue apparaisse encore s'il est résolu.
