### ISSUE TITLE
[ Calculs ] Somme de termes de suite

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#166]
Bonjour à toute l'équipe

_(En préambule : le comportement décrit ici est identique pour le firmware Epsilon E17)_
Après avoir défini la suite u(n) = n dans l'application suite, il est possible d'utiliser les termes de la suite dans l'application "Calculs". Ils sont disponibles en tapant "u(n)" ou à l'aide de la touche "var", ce qui est très pratique.

Par contre, calculer la somme des premiers termes en utilisant la fonction "Somme" de la boite à outil ne fournit aucun résultat : voir copie d'écran ci-dessous.

Amélioration proposée : 
Afficher les résultats lors de l'utilisation d'une suite dans la fonction somme.
Cela permettrait d'aller au-delà des simples sommes de termes consécutifs de la suite, déjà possible directement dans l'application "Suites". 

Copie d'écran : 
La suite définie dans cet exemple : 
![image](https://user-images.githubusercontent.com/98671961/154981964-f3ecc919-58d4-4a44-b015-2f96a2e94a15.png)

Le calcul dans l'application "Calculs" : 
![image](https://user-images.githubusercontent.com/98671961/154984297-162c6242-7a77-4849-a164-5b2a42d9b092.png)

Exemple de ce qu'il serait possible de faire avec l'évolution (la partie de droite serait alors calculée) : 
![image](https://user-images.githubusercontent.com/98671961/154985448-1e59706a-7ef2-4704-abb2-0a14dd555c57.png)

**Comment by Lauryy06** [comment]
Pour avoir eu le même problème je peux confirmer que c'est ennuyeux, je vais voir ce que je peux faire.

**Comment by fmOOmf** [comment]
Bonjour. 
L'étiquette "Bug" est sévère. 
Si la fonction "Somme" n'a pas été prévue pour gérer les suites, il s'agira d'une réelle évolution (et "made in Upsilon".)

**Comment by Lauryy06** [comment]
J'ai choisi cette étiquette car c'est le comportement qu'on attend de la fonction somme.

**Comment by Lauryy06** [comment]
Normalement c'est fixé (f95f9ebb2da25090c22493e602c87a5bc1d6f6d7).

**Comment by fmOOmf** [comment]
Impressionnant ! Bravo !
