### ISSUE TITLE
Epsilon Light theme not working as expected

### ISSUE THREAD

**Issue by LukasMFR** [UpsilonNumworks/Upsilon#177]
**Describe the bug**
When using Epsilon Light theme in Upsilon the icons don't look like the original theme files icons.
The Calculation app has one pixel that is off and the angles of the icons are not "smooth".

**To Reproduce**
Install Upsilon with Epsilon Light theme (or Epsilon Dark)

**Expected behavior**
Should look like the default Epsilon theme

**Screenshots**

Here is a screenshot from NumWorks simulator :
![screenshot (2)](https://user-images.githubusercontent.com/41242166/158586975-165d56ac-b1dc-4ed9-ab58-2acfbc86f723.png)

And here is one from Upsilon theme page :
![epsilon_light](https://user-images.githubusercontent.com/41242166/158587286-c61a0aed-a450-43f3-b577-720e06848f1a.png)

**Device :**
Tested on NumWorks simulator, Upsilon simulator and N0110 running the latest build of Omega (which has the issue too).

I currently have and older commit of Omega with the Epsilon Light theme and everything looks fine.

**Comment by LukasMFR** [comment]
It actually does this for all themes, basically it shifts the second line of pixels by 2 to the left.

**Comment by hugo-b-r** [comment]
It is one of these 3 commits that brings this problem:
![image](https://user-images.githubusercontent.com/75478485/171683487-e54e4243-b1d1-4d79-a978-761e86e81a66.png)

**Comment by Lauryy06** [comment]
Fixed in 992fb5dc85c9abe85f3a9b9eecec24b6839b54ee.
