### ISSUE TITLE
[ Question ] Syntaxe Liseuse

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#178]
Bonjour à tous

Mes premiers essais de création de fichier liseuse ont été infructueux : j'ai utilisé Overleaf, mais la syntaxe de Overleaf n'est pas celle de la liseuse. Je découvre qu'il n'y a pas un standard LaTEX mais tout un univers de grammaires LaTEX.

La question est : 
La syntaxe utilisée par la liseuse est-elle issue d'un standard ? Si c'est le cas, pouvez-vous nous en donner a minima le nom, voire des liens internet que les Upsiloniens puissent consulter ?
L'idée est de pouvoir accéder à la toute la grammaire et aux capacités accessibles, sans vous inonder de questions à la moindre interrogation. Cela va également amorcer la possibilité d'une bibliothèque de contributions issues de la communauté.

Merci à toute l'équipe

**Comment by Yaya-Cout** [comment]
Normalement, les fonctions utilisables sont listée [ici](https://lolocomotive.github.io/Upsilon-website/doc/latex) pour les fonctions classiques et [là](https://lolocomotive.github.io/Upsilon-website/doc/latex) pour les couleurs. Vous pouvez utiliser [ceci](https://github.com/UpsilonNumworks/Upsilon/blob/upsilon-dev/apps/reader/TexParser.md) pour commencer

---

The usable functions are listed [here](https://lolocomotive.github.io/Upsilon-website/doc/latex) for the classics function and [here](https://lolocomotive.github.io/Upsilon-website/doc/latex) for the colours. You can use [this](https://github.com/UpsilonNumworks/Upsilon/blob/upsilon-dev/apps/reader/TexParser.md) to start.

**Comment by fmOOmf** [comment]
Bonjour.
Merci. J'avais bien vu ces informations dans la présentation de la liseuse et le lien associé dans la FAQ. Mais comme certaines possibilités existantes ne sont pas décrites ( la manière d'écrire les exposants, les indices, la manière de décrire les couleurs, les syntaxes avec "$", ) je pensais que l'application se basait sur un standard dont la description se trouvait sur le net.

Peut-être enrichir la description de la liseuse avec : 
L'utilisation de $   (vue dans le fichier d'exemple de liseuse du [post de présentation de Upsilon](https://tiplanet.org/forum/viewtopic.php?f=97&t=25427#p266087) par Critor sur tiplanet)
Indice : X_0  ou U_{2n+1}        (idem)
Exposant : x^2  ou x^{2n+1}  (idem)
Couleur : %x%  et  %\x%   
avec x un code couleur listé ici : (votre 2e lien pointe sur le 1er lien, mais j'ai trouvé grâce à votre 3e lien ) : 
https://github.com/UpsilonNumworks/Upsilon/blob/upsilon-dev/apps/reader/README.md


**Pouvez vous compléter en fournissant les quelques éléments qui me manquent ? :**  
- la manière de choisir la taille de police, 
- les attributs gras, italique, souligné, 
- la manière d'écrire les limites, 
- la syntaxe pour les sommes 
- la syntaxe pour les intégrales 
- les parenthésages
- les symboles de vecteurs (lettres flêchées)
-  les vecteurs et matrices 
- des flèches obliques pour indiquer "croissance et "décroissance"

Merci pour ces renseignements. ☺

**Comment by Yaya-Cout** [comment]
Tout d'abord, je ne crois pas qu'il y ait un standard dans l'application liseuse : nous essayons de traiter les fonctionnalités les plus courantes, mais elle ne sont pas toutes disponibles…
- Les couleurs sont disponibles en bas de ce fichier : https://github.com/UpsilonNumworks/Upsilon/blob/upsilon-dev/apps/reader/README.md
- La taille de police n'est pas changeable pour le moment
- Je ne suis pas sûr qu'il soit possible de souligner (peut-être possible, mais je ne sais pas comment), mettre en gras et l'italique sera possible si #170 est merge
- Pour les limites, les sommes et les intégrales, je ne sais pas si c'est possible
- Pour les parenthèses, vous pouvez utiliser `\left(` et `\right)`
- Pour les vecteurs et matrices, je ne sais pas si c'est possible et comment les faire
- Je pense que les barres obliques pour croissance et décroissance ne sont pas dans la police (peut-être à faire ? Je pense que ce serait facile…)

**Comment by Yaya-Cout** [comment]
Je viens d'implémenter les barres obliques dans #184.

**Comment by fmOOmf** [comment]
:-)  Super ! Merci👍 

Pour les limites, les vecteurs, les sommes, les intégrales, cela pourrait être la même logique que  pour que pour la racine Niemes : sqrt(n){x}. Le symbole (racine) est remplacé par le symbole intégrale ou somme.  Les 2 informations (n) et {x} sont  "juste (!)" à des endroits différents. 

Pour moi j'ai mes informations. **On peut fermer le post.** J'ouvrirai éventuellement des suggestions apres la sortie de la version 1.0 stable.

Merci encore pour cette réactivité.
