### ISSUE TITLE
Sub-menus, toggle switches, and sliders are the wrong color

### ISSUE THREAD

**Issue by penguinencounter** [UpsilonNumworks/Upsilon#181]
**Describe the bug**
Sub-menus, toggle-switches, and sliders in menus are red, not blue, which does not match the rest of the theme.

**To Reproduce**
1. Go to 'Settings'
2. See error

**Expected behavior**
Switches etc. should probably be blue like the rest of the theme, not the red from Omega.

**Screenshots**
![image](https://user-images.githubusercontent.com/49845522/159083805-e3847b34-9e8c-4fba-8af3-f7e7a3e0e969.png)

**Device (please complete the following information):**
 - Web simulator
 - Upsilon Version: 1.0.0-dev
 - Upsilon commit: 373824e

**Comment by hugo-b-r** [comment]
Hello. That's normal it the theme color scheme. If you don't like it feel free to create your own.
