### ISSUE TITLE
android version

### ISSUE THREAD

**Issue by farvardin** [UpsilonNumworks/Upsilon#187]
**Is your feature request related to a problem? Please describe.**
NumWorks and Omega released an android version as APK. Ideally Upsilon could do the same. 

**Describe the solution you'd like**
A bonus could be the android version doesn't reset like the official version does.

**Comment by Yaya-Cout** [comment]
The android simulator already exists, but he isn't in the Google Pay Store… The storage is already saved since Omega does it.

**Comment by farvardin** [comment]
Great. Where can we download it? I couldn't find it. I don't use Google store anyway and prefer a direct APK.

**Comment by Techwizz-somboo** [comment]
When building you probably run `make PLATFORM=android` or something similar

**Comment by Yaya-Cout** [comment]
You can download by cliquing on the first link of this [page](https://github.com/UpsilonNumworks/Upsilon/actions/workflows/ci-workflow.yml?query=event%3Apush+branch%3Aupsilon-dev), then scroll down, and you will see the APK file downloadable if you're logged to GitHub

**Comment by gbraad** [comment]
I am not sure, but the artifacts aren't available to me. They are pushed to Google Storage, but there are no output available to us.

**Comment by Yaya-Cout** [comment]
Are you connected to GitHub ?

**Comment by gbraad** [comment]
I am on GitHub, but not a member of your repo, so perhaps that is the reason?

**Comment by Yaya-Cout** [comment]
No, do you see the artefacts when you scroll down in the run page ? (https://github.com/UpsilonNumworks/Upsilon/actions/runs/2026995445)

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/159671987-afd27304-3065-4249-9248-24e9bf858387.png)

**Comment by Yaya-Cout** [comment]
Click on summary, then scroll down.

**Comment by gbraad** [comment]
How did you get there? As I did not see those in my view.

**Comment by Yaya-Cout** [comment]
![image](https://user-images.githubusercontent.com/67095734/159672234-b7a771ed-22f4-49dd-bbbb-e22d0d4dfcae.png)
![image](https://user-images.githubusercontent.com/67095734/159672297-c6156482-30ea-453d-aa9b-026627717bf2.png)

**Comment by gbraad** [comment]
I do not see this option
![image](https://user-images.githubusercontent.com/1894/159672349-cbb62907-ac1e-4869-97d7-b1dfd947bc52.png)

**Comment by Yaya-Cout** [comment]
Under the title, you have a summary button
![image](https://user-images.githubusercontent.com/67095734/159672482-735dcce2-2573-4668-b570-1c3d13fb582d.png)

**Comment by gbraad** [comment]
Nope, the summary only shows `ci-workflows.yaml`:

![image](https://user-images.githubusercontent.com/1894/159672750-bf34ab7b-e047-413e-aaa1-7592893d4640.png)

**Comment by Yaya-Cout** [comment]
Yes, scroll down on this page.

**Comment by gbraad** [comment]
Oh fuck... I see now what happens... It does load later!
I had to wait longer...

🤦

**Comment by farvardin** [comment]
> You can download by cliquing on the first link of this [page](https://github.com/UpsilonNumworks/Upsilon/actions/workflows/ci-workflow.yml?query=event%3Apush+branch%3Aupsilon-dev), then scroll down, and you will see the APK file downloadable if you're logged to GitHub

ok, thank you, I managed to find it. Maybe you could put a direct link to a release (and stable) version on the home page, like Omega did, it will be more user friendly :) 

However, I can't install this apk on my phone (lineageos 18.1), it just says "application non installée". On my older pocophone with the default OS I can't either (same message). Numworks 17 works perfectly on both. Omega can be installed on both (but only work on the second one, on the first it displays but it's stuck)

**Comment by Lauryy06** [comment]
I think you can reopen this issue on the [website](https://github.com/lolocomotive/Upsilon-website/).
