### ISSUE TITLE
[ Bug mineur ] Nom de couleur

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#192]
Bonjour 
Nouveau cadeau du mois de mars 2022 : la possibilité de changer les couleurs des courbes et suites est arrivée sur la version bêta 👍 

Petit retour : 
En version bêta: les 2 couleurs bleue et Cyan portent le même nom ("bleu").
Idem pour les noms anglais.

{On beta version, Blue and Cyan colours
have the same name "Blue " for functions and sequences. }

**Comment by Yaya-Cout** [comment]
Vous voulez que je corrige ça ?

---

Do you want I fix it ?

**Comment by fmOOmf** [comment]
Upsilon est passé en vitesse lumière. 
☺
