### ISSUE TITLE
[ Enhancement ] raccourci vers paramètres 

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#194]
Bonjour 

Suggestion : ajouter un raccourci pour accéder directement à l'application "parametres".
[Shift] + [ *10^x ] semble un bon candidat.

Merci à vous

{ Add  a shortcut to access directly to "Settings" }

**Comment by Yaya-Cout** [comment]
Je sais qu'il y a déjà `×10**x` pour accéder aux paramètres, mais ce pourrait être une bonne idée de le faire aussi avec `Shift + ×10**x` 

---
I know there is already `×10**x`to access settings, but it may be a good idea to add also the support of `Shift + ×10**x`

**Comment by fmOOmf** [comment]
Oui parce que dans "Calcul" : "*10^x" sert à positionner des puissances de 10. Donc impossible de basculer de "Calculs" vers "Paramètres" avec ce raccourci actuellement.
=> [Shift] + [ *10^x ] permettrait de basculer de "calcul" vers "paramètres" (pratique par exemple pour changer un paramètre de calcul : activation des complexes, les degrés en radians, ...).


Yes. In "Calculation", "*10^x" is already used, preventing to toggle from "Calculation" to "Settings".
[Shift] + [ *10^x ] would allow a direct access from "Calculation" to "Settings" . Useful for instance when one wants to change a math parameter (complex, deg to rad ...)

PS : je ne sais pas comment insérer la barre grise séparant le français de la "traduction de courtoisie".

**Comment by Yaya-Cout** [comment]
Je pense que je vais essayer d'implémenter ça… (PS : Pour la barre grise, essaye de taper `---` avec des nouvelles lignes avant et après les moins…)

---

I think I will try to implement this…

**Comment by fmOOmf** [comment]
Merci !
☺
