### ISSUE TITLE
[ Enhancement ] Swap de position RPN/Fonctions

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#195]
Bonjour

Le raccourci pour aller à "Fonction" est `shift + 9`.
Sauf que dans certaines applications (notamment "Calculs")  `shift + 9` permet d'écrire le symbole omega.
Donc le switch de "Calcul" vers "Fonction" n'est pas possible par raccourci.

Suggestion : inverser la position des applications "RPN" et "Fonction" (les amateurs de la notation polonaise inverse apprécieront).
Cela réintroduit la possibilité de passer de "Calcul" vers "Fonctions" par un `shift + 8`.
NB : le raccourci vers "Calculs" (`shift + 7`) est lui aussi préempté pour écrire le symbole mu, mais comme un 2e raccourci existe pour "Calculs" (`shift + Home`), il n'y a pas de problème pour le trajet vers l'application "Calculs".

---

Shortcut to go to "Function" is `shift + 9`. As `shift + 9` allows to write omega symbol, it is suggested to swap "RPN" and "Functions" location, to access to "Function"  (via a `shift + 8`) from all applications.

**Comment by LukasMFR** [comment]
Pas sûr mais dans build/config.mak il y a la liste des apps, j’imagine qu’il suffit de changer l’ordre.
————
Not sure but in build/config.mak, there is a list of all apps, maybe changing this order may fix that

**Comment by Yaya-Cout** [comment]
Oui, c'est ça

---

Yes, it's this
