### ISSUE TITLE
[apps/python] Key selector is showed in autocompletion

### ISSUE THREAD

**Issue by Yaya-Cout** [UpsilonNumworks/Upsilon#198]
**Describe the bug**
When you type “K” with the `ion` module imported, the autocompletion show “Key selector” as suggestion

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Python app
2. Create a new script
3. Type 
```python
from ion import *
K
```
4. See error.

**Expected behaviour**
Key selector shouldn't appear in the autocompletion

**Screenshots**
![image](https://user-images.githubusercontent.com/67095734/161438800-e97c63ee-0d7e-4d56-8393-7743419dbd5a.png)

**Device:**
 - Devices : My calculator and the Web simulator (I think all platforms are concerned…)
 - Upsilon Version: 1.0.0-dev
 - Upsilon commit: a770ee9

**Comment by ANTARCTUS** [comment]
I don't think we should fix this bug, I use Upsilon very regularly, yet I persist in writing "KEY_" and waiting for autocompletion. With this "bug" it reminds me from the first letter how to write the keys, and in the end it saves me time.

Je ne pense pas que l'on devrait régler ce bug, j'utilise très régulièrement Upsilon, pourtant je persiste à écrire "KEY_" et à attendre l'autocomplétion. Avec ce "bug" cela me rappelle dès la première lettre comment écrire les touches, et au final, il me fait gagner du temps.

**Comment by Yaya-Cout** [comment]
I think I will fix this bug, but I will add a submenu that will contain all the old `KEY_` names to keep autocompletion.

---

Je pense que je vais corriger ce bug, mais que je vais ajouter un sous menu qui va contenir les anciens `KEY_` pour pouvoir les avoir dans l'autocomplétion.

**Comment by ANTARCTUS** [comment]
Why not.
