### ISSUE TITLE
[external] New app pdf reader / porting an existing one

### ISSUE THREAD

**Issue by Mino1289** [UpsilonNumworks/Upsilon#20]
I want to share an idea, that exist on most high quality calculator, like TI-nspire: a PDF reader.

Why ?
- I know that you can read txt with the reader app. But for math equations, LaTeX -> PDF is better and more readable.

If you want more details on what I suggest, I'm free to discuss here or in discord (`Mino#1289`)

**Comment by FaustinM** [comment]
It may be more simple to port a LaTeX parser ?

**Comment by Mino1289** [comment]
> It may be more simple to port a LaTeX parser ?
- I don't know, a LaTeX parser seems complicated (in my point of view), and it come the same question:
LaTeX is producing a pdf file, so how to show that file in the calculator ?

- If it's a LaTeX equation into poincare equation maybe that's cool.

**Comment by Lauryy06** [comment]
I found an open-source library named MuPDF to render pdf files. It may be possible to use it in the reader if it doesn't take too much space.

**Comment by Mino1289** [comment]
This could be perfect !

**Comment by Overengined** [comment]
> I found an open-source library named MuPDF to render pdf files. It may be possible to use it in the reader if it doesn't take too much space.

Seems interesting, but please , please, don't forget the core game here ! PDF is fun, but txt reading should also be possible.
I suggest that the reader should be made in a way that allows both to be read.

**Comment by Lauryy06** [comment]
The .txt files are already readable via the reader app.

**Comment by Overengined** [comment]
> The .txt files are already readable via the reader app.

My bad, apologies

**Comment by apoleon33** [comment]
Do not forget that pdf can fastly be pretty big so idk if it would be that cool
Some of my pdfs are 20mb big.
i don't want to know the number of lines of a .txt to have that...

**Comment by Mino1289** [comment]
> Do not forget that pdf can fastly be pretty big so idk if it would be that cool
> Some of my pdfs are 20mb big.
> i don't want to know the number of lines of a .txt to have that...

The idea of the PDF reader was to put course formulas in a more readable format than in txt. 
And so the files should contain only a few annotations and the formulas so not be too heavy.

**Comment by apoleon33** [comment]
i see 1 reason to put course formulas in a calculator, and its not very legal ;)
idk if u see what i mean
but after all why not?

**Comment by Mino1289** [comment]
> i see 1 reason to put course formulas in a calculator, and its not very legal ;)
> idk if u see what i mean
> but after all why not?

Yes, but do you know the TI-Nspire™ CX II-T CAS?
Except for the baccalaureate and post-prepa exams the exam mode is not all the time required (in my school no need for the exam mode and currently the TI-Nspire have an advantage: pdf files).

**Comment by apoleon33** [comment]
> > i see 1 reason to put course formulas in a calculator, and its not very legal ;)
> > idk if u see what i mean
> > but after all why not?
> 
> Yes, but do you know the TI-Nspire™ CX II-T CAS?
> Except for the baccalaureate and post-prepa exams the exam mode is not all the time required (in my school no need for the exam mode and currently the TI-Nspire have an advantage: pdf files).

ok :)
sorry but im spé nsi

**Comment by Mino1289** [comment]
> > > i see 1 reason to put course formulas in a calculator, and its not very legal ;)
> > > idk if u see what i mean
> > > but after all why not?
> > 
> > 
> > Yes, but do you know the TI-Nspire™ CX II-T CAS?
> > Except for the baccalaureate and post-prepa exams the exam mode is not all the time required (in my school no need for the exam mode and currently the TI-Nspire have an advantage: pdf files).
> 
> ok :)
> sorru but im spé nsi

Strength to you

**Comment by Overengined** [comment]
>  The idea of the PDF reader was to put course formulas in a more readable format than in txt.
And so the files should contain only a few annotations and the formulas so not be too heavy.

yes indeed, but don't you think that LaTex is more appropriated ? I mean, you don't necessarily need to translate your LaTex in pdf rght ? you could make a simple viewer ...

**Comment by Mino1289** [comment]
> > The idea of the PDF reader was to put course formulas in a more readable format than in txt.
> > And so the files should contain only a few annotations and the formulas so not be too heavy.
> 
> yes ideed, but don't you think that LaTex is more appropriated ? I mean, you don't necessarily need to translate your LaTex in pdf rght ? you could make a simple viewer ...

Why not, but I don't know if porting LaTeX to such a small environment makes sense.
But as said above, if we can make a parser to a poincare equation and/or render directly, that's what we need.

**Comment by Overengined** [comment]
>>> The idea of the PDF reader was to put course formulas in a more readable format than in txt. And so the files should contain only a few annotations and the formulas so not be too heavy.

>>yes ideed, but don't you think that LaTex is more appropriated ? I mean, you don't necessarily need to translate your LaTex 
          in pdf rght ? you could make a simple viewer ...

> Why not, but I don't know if porting LaTeX to such a small environment makes sense.
But as said above, if we can make a parser to a poincare equation and/or render directly, that's what we need.

I absolutely agree, but , even if I'm not an expert in the domain, I think it won't be that hard to run a LaTex parser on the NumWorks.

**Comment by Mino1289** [comment]
> > > > The idea of the PDF reader was to put course formulas in a more readable format than in txt. And so the files should contain only a few annotations and the formulas so not be too heavy.
> 
> > > yes ideed, but don't you think that LaTex is more appropriated ? I mean, you don't necessarily need to translate your LaTex
> > > in pdf rght ? you could make a simple viewer ...
> 
> > Why not, but I don't know if porting LaTeX to such a small environment makes sense.
> > But as said above, if we can make a parser to a poincare equation and/or render directly, that's what we need.
> 
> I absolutely agree, but , even if I'm not an expert in the domain, I think it won't be that hard to run a LaTex parser on the NumWorks.

I'm not an expert heren but I'm happy to read that 🙂

**Comment by FaustinM** [comment]
Pdf is a fun project for external, in internal I think we can just improve txt reader for add Poincaré

**Comment by apoleon33** [comment]
> Pdf is a fun project for external

then do it ;)

**Comment by Lauryy06** [comment]
Now reader app supports LaTeX expressions, so can I close it ?

**Comment by Overengined** [comment]
Yes, I think.
