### ISSUE TITLE
[ Liseuse ] Regression sur lettres grecques (Upsilon !)

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#200]
Bonjour à toute l'équipe.

1- Sauf erreur de ma part, quelques lettres grecques ne passent plus (régression pour 1.0.0 dev par rapport à 1.0.0 beta). 
   Dont omega et upsilon (!). Voir ci-dessous.
  
2- Attention aussi : le #184 indique : 
  \ldots to display “┆”
  mais en réalité \ldots affiche "..." (👍  c'est aussi ce qu'affiche \ldots dans d'autres applications LaTex)
  Si vous voulez implémenter  “┆”, cela devrait s'appeler \vdots.

Je joins un fichier urt (copie du contenu ci-dessous, car github ne permet pas d'attacher en PJ un fichier *.urt).
Merci à toute l'équipe

**Fichier Exemple :** 
   - pb sur sigma   : $\sigma$
   - pb sur tau     : $\tau$
   - pb sur upsilon : $\upsilon$
   - pb sur phi     : $\phi$
   - pb sur chi     : $\chi$
   - pb sur psi     : $\psi$
   - pb sur omega   : $\omega$
   - pb sur IOTA : $\Iota$
  
Les lettres suivantes sont OK : 
   $\alpha \beta \gamma \delta \epsilon \zeta \eta \theta \iota \kappa \lambda \mu \nu \xi $
   $\omicron$ $\pi$  $\rho$

   $\Alpha \Beta \Gamma \Delta \Epsilon \Zeta \Eta \Theta \Kappa \Lambda \Mu \Nu \Xi $
   $\Omicron \Pi \Rho \Sigma \Tau \Upsilon \Phi \Chi \Psi \Omega  $

**cdots et ldots :**
   $\cdots$   $\ldots$
   => Points verticaux non présents.
   Ils devront s'appeler vdots si implémentés.

**Comment by Yaya-Cout** [comment]
Oui, j'ai oublié de mettre à jour mon message après avoir corrigé le comportement de `\ldots`… Si vous voulez, je peux rajouter `\vdots`…

---

Yes, I forgot to update my message after fixing `\ldots`… If you want, I can implement `\vdots`

**Comment by fmOOmf** [comment]
Bonsoir

Perso, je ne l'utilise pas. Je pense que c'est surtout utilisé pour les matrices.
Par contre :  intégrales, limites,  sommes ... quand vous aurez retrouvé un peu de bande passante, et que se sera implémenté, vous ferez des heureux.

---

No thanks.

**Comment by fmOOmf** [comment]
Par contre, avez-vous une idée pour les lettres grecques sigma, tau, upsilon, phi, chi, psi, omega et IOTA ?

**Comment by Lauryy06** [comment]
Pour une raison que j'ignore, j'ai eu le bug mais il a disparu après une recompilation d'une de mes branches où je travaille sur la liseuse, sauf pour Iota.

---

For some reason, I had the bug but it disappeared after a recompilation of one of my branches where I work on the reader, except for Iota.

**Comment by fmOOmf** [comment]
Apparemment Iota majuscule peut être écrit avec un i majuscule. Je ne sais pas si ça aide ...

---

Capital Iota can be written as capital "i"

**Comment by Lauryy06** [comment]
Normalement le bug n'est plus présent, puis-je fermer l'issue ?

---

Can I close the issue ?

**Comment by fmOOmf** [comment]
Oui. 
Un pas de plus vers la perfection.
:-)
