### ISSUE TITLE
Crash de Upsilon avec abus du RPN

### ISSUE THREAD

**Issue by Golem642** [UpsilonNumworks/Upsilon#206]
**Décrivez le bug**
Crash de la calculatrice avec l'utilisation du RPM

**Comment reproduire**
1. Allez sur RPM
2. Appuyez sur "2" 2 fois puis sur *
3. Appuyez sur "EXE" puis sur *, et répéter ces 2 commandes jusqu'à ce que le nombre disparaisse
4. Multipliez par n'importe quoi

**Réaction attendue**
Crash de Upsilon, des fois même l'écran de crash est bugué

**Device (please complete the following information):**
 - Sur Numworks n110
 - Version d'Upsilon : 1.0.0 dev
 - Upsilon commit: public

**Comment by fmOOmf** [comment]
Hello.
Tu parles bien de l'application RPN ?
Pour moi pas de crash, j'ai fait : 
- Tes étapes 1 et 2 : `2 EXE` **=> 2**, puis  `2 EXE` **=> 2  et 2**,  puis ` * ` **=> 4,**
- Ton étape 3 : ` EXE `**=> 4 et 4**, puis  ` *  `**=> 16**
- "jusqu'à ce que le nombre disparaisse" : ` *  `**=> 0**, puis ` *  `**=> 0**, puis ` *  `**=> 0** etc...
   J'obtiens toujours **0**. Le nombre ne disparait pas.
- Ton étape 4 : "Multipliez par n'importe quoi". Je fais `2 EXE` **=> 0  et 2**,  puis ` * ` **=> 0,**
  Donc pas de crash pour moi. Je suis en 1.0.0 dev aussi.

Ma séquence est bonne ?

**Comment by Golem642** [comment]
> - "jusqu'à ce que le nombre disparaisse" : ` *  `**=> 0**, puis ` *  `**=> 0**, puis ` *  `**=> 0** etc...
>    J'obtiens toujours **0**. Le nombre ne disparait pas.

Il faut réappuyer sur exe pour refaire apparaître le dernier nombre avant d'appuyer sur *. Aussi, attendez bien que les opérations se finissent complètement avant de répéter EXE puis *

**Comment by fmOOmf** [comment]
OK. Reproduit; 
Ton test élève au carré le nombre précédent, jusqu'à arriver à un nombre trop grand (plus affiché). Et c'est celui là qui déclenche le crash quand on l'utilise dans un nouveau calcul.
Bien vu.
Je détaille pour les équipes Upsilon : 
- Tes étapes 1 et 2 : `2 EXE `=> **2**, puis `2 EXE` **=> 2 et 2**, puis ` * `**=> 4**,
- Ton étape 3 : `EXE`**=> 4 et 4,** puis `*` **=> 16**
- "jusqu'à ce que le nombre disparaisse" : 
    `EXE`**=> 16 et 16**, puis ` * `**=> 256**,    
    `EXE`**=> 256 et 256**, puis  `* `**=> 65536**, 
    etc ...
   Effectivement, à un moment le nombre n'est plus affiché.
- Ton étape 4 : "Multipliez par n'importe quoi". Je fais `2 EXE` **=> rien et 2**, puis` * `**=> CRASH**

**Comment by Golem642** [comment]
En bonus j'ai même réussi à glitcher l'écran de crash d'Upsilon ! :) (Il restait encore quelques morceaux de l'écran du RPM il y avait des lignes de pixels cassées)

**Comment by Lauryy06** [comment]
This looks like #45...

----

Cela ressemble à #45...

**Comment by Lauryy06** [comment]
Now fixed cec75bfaedae82fd2746eb1d37a62140b87d292a.
