### ISSUE TITLE
Impossible to build binpack

### ISSUE THREAD

**Issue by hugo-b-r** [UpsilonNumworks/Upsilon#209]
**Describe the bug**
When trying to build binpack, it returns an error: "file maybe already patched"

**To Reproduce**
Build latest upsilon-dev or just look at the [CI/CD](https://github.com/UpsilonNumworks/Upsilon/runs/5804868020?check_suite_focus=true)

**Expected behavior**
I really don't understand what's happening. Maybe that having bootloader binpack make make go like there's too much.
**Screenshots**

**Device (please complete the following information):**
-binpack for n0110
-latest upsilon: [5365718](https://github.com/UpsilonNumworks/Upsilon/commit/5365718761013db0c9fe707e9224f6f02f99f16e)

**Comment by Yaya-Cout** [comment]
The latest CI hasn't this bug…

**Comment by Lauryy06** [comment]
The CI crashes before reaching binpack...

**Comment by hugo-b-r** [comment]
Yes but why does it crashes ? I have the same problem on my computer

**Comment by Lauryy06** [comment]
This is a problem with the USB protection and the bootloader (to make a long story short the area where the "magic" key was stored is used by data at 0xFF now, against 0x00 before). I don't know why, but it should be fixed with #205 (as this system changes).
