### ISSUE TITLE
Python division not exact

### ISSUE THREAD

**Issue by Golem642** [UpsilonNumworks/Upsilon#218]
**Describe the bug**
Sometimes when dividing a number in Python that gives an integer result, it display it followed by a lot of zeros and a 1

**To Reproduce**
1. Go to Python
2. Click on Console
3. Execute `132/2`

**Expected behavior**
The divided number should have a lot of zeros followed by a 1 at the end, this only apply to some divisions. Another working example is `51/1`

**Device**
 - Numworks n110
 - Upsilon Version: 1.0.0-dev
 - Upsilon commit: public

**Comment by Yaya-Cout** [comment]
I think it's a precision bug.

**Comment by Lauryy06** [comment]
Yes, it's the imprecision of floating point numbers, a problem that affects computers since the beginning of computing and that we can't fix.
