### ISSUE TITLE
[ Calculs ] Ajouter la fonction produit scalaire (menu matrices de la boite à outils)

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon#219]
Suggestion : 
Enrichir les fonctions proposées dans le menu "matrices" de la boite à outils avec la fonction produit scalaire : 
Entre 2 vecteurs u et v dans un système de coordonnées (x,y,z,...) : 
scal(u,v) = xu*xv + yu*yv + zu*zv + ...
Erreur à produire si les vecteurs n'ont pas la même dimension.
On peut je pense tolérer que les vecteurs soient en ligne ou en colonne.

A voir pour python si la fonction est absente également.

---

It is suggested to add the scalar product function to the "matrix" menu in the Toolbox for "Calculation" App.
May also be added to python library if not already included.

**Comment by fmOOmf** [comment]
noloiV sorG nous a éclairé : le produit scalaire est présent : fonction **dot** dans le menu **Vecteurs**
=> Issue à refuser.
Désolé.

---

Already existing : dot function in Vector menu. Issue to close.

**Comment by Yaya-Cout** [comment]
I close it ?

**Comment by fmOOmf** [comment]
Yes dsl
