### ISSUE TITLE
Too much actions in Python make Upsilon reset without crash error

### ISSUE THREAD

**Issue by Golem642** [UpsilonNumworks/Upsilon#226]
**Describe the bug**
When you move too fast bewteen some python script and the python script list, Upsilon does a straight-up reset without displaying the crash error

**To Reproduce**
1. Go to Python
2. Click on a script to open it
3. Go back
4. Repeat the steps 2 and 3 until it crashes (normally after 2 repeats)

**Expected behavior**
Upsilon should reset without showing the crashing error

**Device (please complete the following information):**
 - Numworks n110
 - Upsilon Version: 1.0.0
 - Upsilon commit: public

**Comment by LukasMFR** [comment]
I have something similar, basically :
I got to Python (with no script as Upsilon does not have defaults scripts) then I click on OK a lot of times (so it gets into the script and out) and after awhile it crashes and I loose the Python file.

**Comment by Overengined** [comment]
Had that one too. Very frustrating, because I was just spam clocking ok on python because of boredom and my calculator crashed. It was not a good experience. 
Would it be some kind of unmanageable memory overload ?

**Comment by Overengined** [comment]
> **Expected behavior** 
> Upsilon should reset without showing the crashing error

@Golem642  , I think you meant **with** a crashing error message. Though I would simply have put here "calculator should be able to handle a high input rate/mass input"

**Comment by Golem642** [comment]
> > **Expected behavior**
> > Upsilon should reset without showing the crashing error
> @Golem642  , I think you meant **with** a crashing error message. Tho I would have put here simply the fact that the clauclator should be able to handle a high input rate.

nope, for me it's doesn't show anything and straight up reset

**Comment by Overengined** [comment]
> > > **Expected behavior**
> > > Upsilon should reset without showing the crashing error
> > > @Golem642  , I think you meant **with** a crashing error message. Tho I would have put here simply the fact that the clauclator should be able to handle a high input rate.
> 
> nope, for me it's doesn't show anything and straight up reset

What you're saying is that your calculator is resetting without an error message and you expect her not to show an error message, that's at leats what I understand by "Upsilon should reset without showing the crashing error".

**Comment by Golem642** [comment]
@Overengined no but like you know, normally when Upsilon crash it shows the "Upsilon Crash !" screen, but here it doesn't. That's what i'm trying to say

**Comment by LukasMFR** [comment]
I am not sure at all but don't you need the bootloader to get the crash screen ? It's like you don't get USB protection if you don't have the bootloader

**Comment by Yaya-Cout** [comment]
It is fixed by 36fa4a4152cf9dbe9cbb4bcf56cf5d40e3877302
