### ISSUE TITLE
Can't build on Arch Linux even on GCC 10

### ISSUE THREAD

**Issue by GitEz-code** [UpsilonNumworks/Upsilon#229]
I tried multiple version from Arch repos, and even in the archives with always the same error:

```
/usr/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/10.1.0/thumb/v7e-m+fp/hard/libgcc.a(_aeabi_ldivmod.o): in function `__aeabi_ldivmod':
(.text+0x32): prohibited cross reference from .text.internal to `__udivmoddi4' in .text.external
/usr/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: (.text+0x4c): prohibited cross reference from .text.internal to `__udivmoddi4' in .text.external
/usr/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: (.text+0x6e): prohibited cross reference from .text.internal to `__udivmoddi4' in .text.external
/usr/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: (.text+0x8a): prohibited cross reference from .text.internal to `__udivmoddi4' in .text.external
collect2: error: ld returned 1 exit status
make: *** [build/rules.mk:83 : output/release/device/n0110/epsilon.elf] Erreur 1
```
(i'm sorry for my bad english)

**Comment by Yaya-Cout** [comment]
I am using the `arm-none-eabi-gcc` package at the latest version (12.1.0) and it works. Can you try to upgrade your system using `pacman -Syu` (or the wrapper for AUR, if you want) ?

**Comment by Tunas1337** [comment]
I'm unsure where you got 12.1.0 from; the latest I see is 11.2.0, which did not work.
However, the NumWorks site offers an alternative, which worked for me: a standalone copy of the toolchain to be placed in a folder and included in the PATH. See the relevant section in the guide on [Installing the SDK](https://www.numworks.com/resources/engineering/software/build/#debian-or-ubuntu), also copied below for your convenience:

You’ll also need to install the latest version of GCC and make it available in your $PATH:

- Download the [GCC toolchain distributed by ARM](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads). You should obtain a gcc-arm-none-eabi-x-linux.tar.bz2 file.
- Decompress that file with `tar xvfj gcc-arm-none-eabi-*-linux.tar.bz2`
- Add the resulting folder to your $PATH. If you use bash, ``echo "export PATH=\$PATH:`find $(pwd)/gcc-arm-none-eabi-*-update/bin -type d`" >> ~/.bashrc`` should do what you need (you’ll need to restart your terminal afterwards).

**Comment by Yaya-Cout** [comment]
It is for Msys2, not for Arch Linux

**Comment by Tunas1337** [comment]
Do you mean the instructions given, or GCC 12.1.0? The instructions worked alright for me on Arch, and I think they worked for the person who opened the last issue about not being able to compile on Arch.

**Comment by Yaya-Cout** [comment]
I mean the given instructions : It works perfectly on my fresh installation of Arch…

**Comment by GitEz-code** [comment]
did the Msys2 instruction work on arch ? for now, i'm using a docker with ubuntu

**Comment by Yaya-Cout** [comment]
I just built Upsilon, and installed missing packages thought pacman when I had errors… I don't think that the Msys2 installation is made for Arch Linux because Msys2 is on Windows.

**Comment by GitEz-code** [comment]
the problem was reported here too, the solution they give doesn't work for me. #191

**Comment by GitEz-code** [comment]
I'll try to upĝrade, I'll keep you posted.

**Comment by Yaya-Cout** [comment]
Are you using a custom theme ?

**Comment by Yaya-Cout** [comment]
I think your bug come from the missing `MODEL=bootloader` in the build command.

**Comment by GitEz-code** [comment]
I upgraded my system, but there still the same issues,  It build perfectly well on the docker so it's not a problem of Upsilon. I made `make clean` before building. I'm not at home so I can't try on a other computer.

**Comment by Yaya-Cout** [comment]
Can you try to build using `make binpack MODEL=bootloader` after a `make cleanall` ?

**Comment by GitEz-code** [comment]
I don't have access to my computer yet, I will try later

**Comment by GitEz-code** [comment]
look like it worked, but how can i flash it to the numworks ? when i do make epsilon_flash, it just rebuild (with the same error)

**Comment by Yaya-Cout** [comment]
`make epsilon.A_flash MODEL=bootloader` for the slot A

**Comment by GitEz-code** [comment]
have i to install a bootloader ? or is it ok without one ?

**Comment by GitEz-code** [comment]
### Instruction en Français

Cette fois ça marche parfaitement. je vais quand même donner les instruction pour ceux qui aurais besoin.

Déja, si vous avez tenter de build sans succès, commencer par faire `make cleanall`. Ça va permettre de supprimer le dossier output qui a échouer.

Ensuite, entrer cette commande: `make binpack MODEL=bootloader -j4`.

Pour finir, enter : `make epsilon.A_flash MODEL=bootloader` pour le flasher dans la Numworks
Lors de mon premier essai, la calculatrice donnais aucun signe de vie. Si c'est aussi votre cas, appuyez simplement sur le bouton RESET au dos de la calculatrice. 

### Instruction in English

This time it works perfectly. I will still give the instructions for those who would need.

First of all, if you have tried to build without success, start by doing `make cleanall`. This will remove the output folder that failed.

Then enter this command: `make binpack MODEL=bootloader -j4`.

Finally, enter: `make epsilon.A_flash MODEL=bootloader` to flash it in the Numworks
On my first try, the calculator gave no sign of life. If this is also your case, simply press the RESET button on the back of the calculator.
