### ISSUE TITLE
Add a link to the external and wallpaper installation site in README

### ISSUE THREAD

**Issue by TomVdt** [UpsilonNumworks/Upsilon#24]
Hello!
As the title says, could we add a link to https://lauryy06.github.io/Upsilon-External/ in the README?
It would make it clear how to "install" a wallpaper.

**Comment by apoleon33** [comment]
According to myself
i think there would be 2 options:
something like this (but with a link etc):
 <a href="https://github.com/Lauryy06/Upsilon/issues"><img alt="Issues" src="https://img.shields.io/github/issues/Lauryy06/Upsilon.svg?labelColor=292929&logo=git&style=for-the-badge" /></a>

 or  a section at the end like this:
## useful links
- <a href="">official website</a>
- <a href="https://lauryy06.github.io/Upsilon-External/">external app (and wallpapers)</a>
- etc

**Comment by TomVdt** [comment]
To me option 2 seems the best and most future proof.
We could also use it to add things like a link to the ulab docs

**Comment by Lauryy06** [comment]
Done https://github.com/Lauryy06/Upsilon/commit/400d03ebdb7d88145051a0dad150bee31fdd64ce
