### ISSUE TITLE
Upsilon crashes when opening and closing python script multiple times

### ISSUE THREAD

**Issue by Axxiar** [UpsilonNumworks/Upsilon#244]
**Upsilon crashes and send me to the bootloader**
When i create a new python script, close it and reopen it 3 time, the calculator crashes

**To Reproduce**
1. Go to Python 
2. Create a new script
3. Open it and Close it (2 or 3 times)

**Expected behavior**
The calculator crashes and the Recovery Mode message shows up
**Screenshots**
![IMG_20220529_172927](https://user-images.githubusercontent.com/70155662/170877743-19f78168-e632-471a-bd68-92b630553e60.jpg)

**Device (please complete the following information):**
 - Device :  n0110 
 - Slot A : Upsilon 1.0.0 (commit : ed20d0e)
 - Slot B : Epsilon 18.2.0

**Comment by Yaya-Cout** [comment]
It's fixed in the development branch.

**Comment by Axxiar** [comment]
And i had the same bug with Scipy module when running the `spy.signal.sosfilt()` function

**Comment by Yaya-Cout** [comment]
Can you open a new issue for it ?

**Comment by Axxiar** [comment]
Sure thank you
