### ISSUE TITLE
Images for the themes on the installation website page are not shown.

### ISSUE THREAD

**Issue by MaxenceDC** [UpsilonNumworks/Upsilon#246]
**Describe the bug**
The images meant to show the look of each theme are missing on the installation page of the website over at [https://getupsilon.web.app/install/](https://getupsilon.web.app/install/).

**To Reproduce**
1. Go to [the installation page](https://getupsilon.web.app/install/).
2. Click on `Theme`.
4. Contemplate those beautiful missing images.

**Expected behavior**
The images should be here, but sadly, they aren't.

**Screenshots**
![image_missing](https://user-images.githubusercontent.com/77689281/170892071-7e12291b-30c4-41b9-9392-5fe0f86160a1.png)

**Device (please complete the following information):**
 - Obviously, using a Chromium-based web browser because WebUSB, you know.
 - If that's relevant, I use Arch, btw.

**Comment by apoleon33** [comment]
maybe move to https://github.com/UpsilonNumworks/Upsilon-website ?

**Comment by Yaya-Cout** [comment]
I can't transfer it, but I fixed it in UpsilonNumworks/Upsilon-Website#28, and you can see the preview [here](https://getupsilon.web.app/doc/themes).

**Comment by Lauryy06** [comment]
So can I close it ?
