### ISSUE TITLE
KhiCAS - Issue with *10^ key

### ISSUE THREAD

**Issue by bernardo7894** [UpsilonNumworks/Upsilon#249]
**Describe the bug**
The `*10^x` key behaves differently in KhiCAS, writing out `10^` rather than `*10^`.

**To Reproduce**
1. Open KhiCAS
2. Type out 

**Expected behavior**
It should add a multiply sign `*` before the 10, unlike in every other application. It's slightly more time-consuming to have to write out the multiply sign each time, or to type an `e` instead.

**Device (please complete the following information):**
 - N0110
 - Upsilon Version: 1.0.0
 - Upsilon commit: ed20d0e

**Comment by Yaya-Cout** [comment]
Can you send a message to Mr Parisse or move this issue to the External repo ?

**Comment by Lauryy06** [comment]
Yes, we are not responsible for KhiCAS.
