### ISSUE TITLE
Rajout du mode, du produit et de la moyenne géométrique dans l'application Statistiques.

### ISSUE THREAD

**Issue by ANTARCTUS** [UpsilonNumworks/Upsilon#261]
Dans l'application "Statistiques" et son onglet "stats". On pourrait rajouter une ligne pour le mode (valeur du plus grand effectif), pour le produit (chaque élément multiplié entre eux) et pour la moyenne géométrique (racine n-ième du produit, avec n l'effectif total).

Et pour simplifier la lisibilité de l'onglet, on pourrait en réorganiser les lignes. En rassemblant la moyenne, moyenne géométrique, médiane et mode. Et en mettant le produit à côté de la somme.

Dernière possibilité, on pourrait rajouter l'écart moyen (https://fr.wikipedia.org/wiki/Écart_moyen) et le mettre à côté de l'écart type, mais on l'utilise peu et risque de faire doublon avec ce dernier. C'est donc à voir.

--------------------------------

In the "Statistics" application and its "stats" tab. We could add a line for the mode (value of the largest number), for the product (each element multiplied together) and for the geometric mean (n-th root of the product, with n the total number).

And to simplify the readability of the tab, we could reorganize the lines. By gathering the mean, geometric mean, median and mode. And putting the product next to the sum.

Last possibility, we could add the average deviation (https://en.wikipedia.org/wiki/Mean_absolute_difference) and put it next to the standard deviation, but we use it little and risk duplicating it . It is therefore to be seen.

--------------------------------
![Maintenant](https://user-images.githubusercontent.com/87766656/176254914-e2cc9e67-41dd-4893-95ba-6e78bba73f92.png)
![Futur](https://user-images.githubusercontent.com/87766656/176254908-10333d3a-5282-4ccf-a863-2d4d209457c5.png)

**Comment by Lauryy06** [comment]
Je vois l'intêret de la moyenne géométrique (on pourrait même rajouter la moyenne harmonique !), ainsi que celle du mode, mais j'ai plus de mal pour le produit, avez-vous un exemple où il peut-être utile ?

---

I see the interest of the geometric mean (we could even add the harmonic mean!), as well as that of the mode, but I have more trouble with the product, do you have an example where it can be useful?

**Comment by Lauryy06** [comment]
Done in 77167d17068fd260bb8994f781d4ee72a033d1cd. Also thanks for the pictures and the info on discord, it was very useful.
