### ISSUE TITLE
Shift + Ans make calculator crash at boot when connected to computer

### ISSUE THREAD

**Issue by Yaya-Cout** [UpsilonNumworks/Upsilon#273]
**Describe the bug**
When the calculator is connected to the computer during Upsilon boot, it crash when exiting the USB menu.

**To Reproduce**
1. Plug the calculator to the computer
2. Go to the bootloader
3. Start Upsilon slot
4. Disconnect the calculator

**Expected behavior**
It shouldn't crash

**Device (please complete the following information):**
 - N0110 with bootloader
 - Upsilon Version: 1.0.1-dev
 - Upsilon commit: a1e213ac91466c29a635c73c697a0c83f7eb6582

**Comment by AngeDieu** [comment]
It doesn't seem to crash with me (commit a124ed7).
