### ISSUE TITLE
"Some"+"Thing" don't work

### ISSUE THREAD

**Issue by BloomyInDev** [UpsilonNumworks/Upsilon#275]
**Describe the bug**
"Some"+"Thing" don't work

**To Reproduce**
1. Go to Python
2. Create a script
3. Create a variable like `var = "Some"+"Thing"` and print it
4. Execute
5. See the error

**Expected behavior**
It's print SomeThing

**Device (please complete the following information):**
 - N0110
 - Upsilon Dev

**Comment by Yaya-Cout** [comment]
It's normal : If you want a space, you need to run `var = "Some" + " Thing"` (add a space), alternatively, you can use `print("Some","Thing")` if you don't want to use spaces. You can test on CPython (official PC Python version).
