### ISSUE TITLE
Avoir un système de vérification que l’os n’a pas été modifié

### ISSUE THREAD

**Issue by ImpotStite** [UpsilonNumworks/Upsilon#282]
Avoir un système de vérification que l’os n’a pas été modifié à l’exemple de khi pour les exams qui pourrait être sur le site d’upsilon. Facile et assez rapide à utiliser pour les examinateurs (ps: j’ai la flemme de repasser sous epsilon pour le bac)

**Comment by Lisra-git** [comment]
Un tel système n'a aucune valeur légale.
Aucun investissement ne sera fait dans ce sens.

**Comment by ImpotStite** [comment]
Dommage mais donc la vérification khi n’a aussi aucune valeur légale?

**Comment by Lisra-git** [comment]
Aucun système légal déclaré, géré par une entité qui pourrait le gérer à son avantage, aucun facteur légal.

**Comment by ImpotStite** [comment]
Ok merci pour la réponse si rapide
