### ISSUE TITLE
Nouveau système de coloration

### ISSUE THREAD

**Issue by ImpotStite** [UpsilonNumworks/Upsilon#283]
Je propose un nouveau système de coloration des script python à la visual studio code car je trouve que la coloration de epsilon est très terne et on s’y perd assez facilement contrairement à celle de vos qui est plutôt pas mal.

**Comment by ImpotStite** [comment]
Et aussi en y repensant pour compléter cette option, on pourrait activer un mode sombre mais que sur python. Car personnellement j’aime pas trop les modes sombres mais sur python c bien pratique

**Comment by Yaya-Cout** [comment]
You can use a custom theme to change the Python editor's colors, if you want. You can use Omega Theme Maker to create a custom color thème, if you want : https://tiplanet.org/forum/viewtopic.php?p=267388 (link in French)
