### ISSUE TITLE
Modifier message

### ISSUE THREAD

**Issue by Ashokaas** [UpsilonNumworks/Upsilon#293]
Bonjour,
Comment je pourrais faire pour modifier le truc et changer le message du mode examen ?
![image](https://user-images.githubusercontent.com/99681959/198049586-aa71b537-e8a2-45e2-b774-fecc17d11330.png)

**Comment by LisraCalco** [comment]
Pourquoi faire?

**Comment by BloomyInDev** [comment]
Voir [ceci](https://github.com/numworks/epsilon/issues/1302)

**Comment by quentinguidee** [comment]
@Ashokaas Si tu as trop peur, tu peux simplement installer Epsilon le temps de l'examen

**Comment by BloomyInDev** [comment]
> @Ashokaas Si tu as trop peur, tu peux simplement installer Epsilon le temps de l'examen

Ou utiliser omega qui n'a pas ce message

**Comment by Ashokaas** [comment]
> > @Ashokaas Si tu as trop peur, tu peux simplement installer Epsilon le temps de l'examen
> 
> Ou utiliser omega qui n'a pas ce message

Oui je sais mais Epsilon est plus complet qu'Omega, il y a des fonctionnalités intéressantes dessus.

**Comment by hugo-b-r** [comment]
Tu peux installer epsilon 18.2.0 qui permet toujours de revenir sur upsilon : http://guide.getomega.dev
Support et fichier necessaire sur lz discord, voir le readme

**Comment by BloomyInDev** [comment]
@Ashokaas si tu as plus besoin il y a moyen de fermer l'issue ?
