### ISSUE TITLE
Bug : Involuntary reset of the calculator (Whith Reader)

### ISSUE THREAD

**Issue by Armand-933** [UpsilonNumworks/Upsilon#307]
**Description**
When I turn off then turn on my calculator, the Reader RESET my calculator when I open a file.

**To reproduce**
1. Turn off the calculator
2. Turn on the calculator
3. Launch the Reader
4. Open a file
When I do this, the calculator got reset.
(I put a .txt file in my calculator with https://upsilonnumworks.github.io/Upsilon-External/ website.)
PS : After that, I can close the reader and re-open it many times and it's working but if i'm turn off my calculator and re-turn on, the bug is here again and the calculator got reset if I open a file into the Reader.

**Expected behavior**
I expected open my file (.txt) without reset of my calculator.

**Device**
- N110
- 1.0.1
- Public

**Comment by Dreaming-Codes** [comment]
My calculator crash when I open the same file for more than one time for reset, same device and version
