### ISSUE TITLE
Problem during compilation

### ISSUE THREAD

**Issue by Nenyoko** [UpsilonNumworks/Upsilon#309]
Hi,
this morning I tried to compile Upsilon, so I installed the dependencies and I entered this command in order to compile : 
make OMEGA_USERNAME="" binpack -j4
(BTW, my OS is a Linux Mint 21 64 bit, but I don't think it really matters.)
Then I got this error during the compilation :
![image](https://user-images.githubusercontent.com/59934079/210163766-f18b7f06-5c83-447c-91dc-fe59347892a6.png)

Here is when I tried again : 
![image](https://user-images.githubusercontent.com/59934079/210163881-cba6893e-fb04-4b43-8b3d-8f3e94dfce1d.png)

I hope you guys could fix it, I can't really help more than warning about this error.
Happy new year and have a nice day everybody :smiley:

**Comment by Yaya-Cout** [comment]
I am sorry about this error. It's a mistake in my last commit. 
I just fix it, so you have to run `git pull` then `git submodule update` to get the fix.
Happy new year !
