### ISSUE TITLE
Language and country settings don't show up on startup anymore

### ISSUE THREAD

**Issue by Dan3a** [UpsilonNumworks/Upsilon#312]
**Describe the bug**
On calculator reset, the language and country settings do not appear.

**To Reproduce**
1. Press the reset button
2. Get directly sent to home screen with default settings (English-US)

**Expected behavior**
Should show the country and language settings

**Device (please complete the following information):**
 - Compiled on arch, using n0110
 - Upsilon 1.0.1-dev
 - Upsilon commit: 72d10f8

**Comment by Dan3a** [comment]
oops

**Comment by Yaya-Cout** [comment]
If you want onboarding, compile with `epsilon.onboarding` instead of `epsilon` in your command : if you are building with `make epsilon.A_flash`, just use `make epsilon.onboarding.A_flash`. It should fix your problem.

**Comment by Dan3a** [comment]
Yep alright that works, thanks!
