### ISSUE TITLE
Unable to Flash (WSL2 via Binpack)

### ISSUE THREAD

**Issue by imreallyliam** [UpsilonNumworks/Upsilon#40]
**Describe the bug**
When flashing, the same way as Omega, the calculator does not boot and requires a recovery via Omega's website.

**To Reproduce**
1. Build using WSL2 and Ubuntu
2. Flash using WebDFU

**Expected behavior**
It boots.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Latest Upsilon

**Comment by Lauryy06** [comment]
Before doing a recovery, did you try resetting your Numworks ?

**Comment by imreallyliam** [comment]
I did not, just a restore. Should I try a reset?

**Comment by Lauryy06** [comment]
Yes
