### ISSUE TITLE
[apps/calculation] Add Dimension in additionnal result of Units calculation

### ISSUE THREAD

**Issue by Mino1289** [UpsilonNumworks/Upsilon#43]
I would like to share an idea, for the calculation application. 

Add the dimension of the result after a unit calculation. Currently, there is the conversion to SI Unit, I think we can rely on it to make a dimensional calculation. 
I think we can put this dimensional result below the conversion in SI units.

Here is the list of SI units related to their dimension:
| SI Unit | Dim |
| :---: | :---:|
| m | L |  
s | T
kg | M
A | I
K | θ
mol | N
cd | J

**Comment by Lauryy06** [comment]
Done ! e8ea693e5c716174401b2c7552655a0930e506b1
