### ISSUE TITLE
RPN bug that resets the calculator (+ hypothesis on cause)

### ISSUE THREAD

**Issue by Overengined** [UpsilonNumworks/Upsilon#45]
**The bug in itself and how to reproduce it:** 

1.Enter numbers until you fill the memory.
2. Using the arrow keys, select the last entered number.
3. Using the erase key, delete all the numbers in the list, but do not go back to the input box at any time during this phase.
4. Once you've erased all the numbers in the list, check that no cursor can be found in the input box, if there is one, you must start again.
5. Press once the down arrow key so that the cursor appears on the input box.
6. Enter a number and press + , if you've done everything correctly, the calculator crashes and resets.

**My hypothesis on why this happens and how it might be fixed:**
I've observed that during the steps 4,5, and 6, a realy thin grey box appears on the top of the screen, as if the calculator would be trying to select a "ghost" item (the gray used is the same to highlight selected elements). I think that what happens, is that the calculator tries to do an operation on a selected element that doesn't exist, or at least doesn't have a value, and that causes the crash.
Another element that tends to show that my theory might be right is that, if you do step 6 but without doing an operation and instead simply pressing ok to add the number to the list, nothing abnormal happens.

small note : a similar issue was made by someone else on Omega (apoleon33) , he kindly allowed me t use the gif he made , it can be found [here](https://drive.google.com/file/d/1mjJ8CcKCCbunCUu42Pn9CC4DONb3mp6u/view?usp=sharing) (be aware, it's a big file).

**Comment by Syycorax** [comment]
Fmmpeg-ed the gif to [mp4](https://user-images.githubusercontent.com/54723548/136656500-bef8e33b-1a55-41a3-aab4-933e3e854af0.mp4), the video is now way smaller

**Comment by RedGl0w** [comment]
![image](https://user-images.githubusercontent.com/43498612/139570884-a39d98e2-a5a9-42bd-9e7d-a185e18e6a9f.png)

**Comment by Lauryy06** [comment]
Can I close this issue ?

**Comment by Overengined** [comment]
> Can I close this issue ?

I don't think, since I don't have seen any hanges been done to the Upsilon repo yet, I think we shall wait.

**Comment by Lauryy06** [comment]
It's done

**Comment by shaunsingh** [comment]
@Lauryy06 can you pull the changes into your fork (https://github.com/Lauryy06/Upsilon-RPN), its what's used for the submodule

**Comment by Lauryy06** [comment]
Oh sorry, I modified the submodule but I forgot to push the changes. I'll do it as soon as possible, thanks for reminding me!

**Comment by Lauryy06** [comment]
This time it's really done.

**Comment by apoleon33** [comment]
wait that was my issue lol

https://github.com/Omega-Numworks/Omega/issues/432

cool its finally solved ^^
