### ISSUE TITLE
[RPN] Line with random colors after restarting

### ISSUE THREAD

**Issue by lolocomotive** [UpsilonNumworks/Upsilon#57]
**Describe the bug**
The bar that is grey when the RPN app in empty becomes random color after restarting the calculator

**To Reproduce**
1. Go in the RPN App
2. Turn off the calculator
3. Turn it back on
4. There is a line with random colors

**Expected behavior**
The line should be grey

**Screenshots**
![DSC_0012](https://user-images.githubusercontent.com/49951010/138549205-17877b3d-13ee-4f26-bbe6-e56906edce07.JPG)
<br>
On the image the line doesn't look very colorful but it is

I'm using upsilon commit 0550b66 with a custom theme

**Comment by shaunsingh** [comment]
I had the same issue, although just hitting clear twice made it go away.

**Comment by lolocomotive** [comment]
Yes it goes away really easily and does not affect usability, it's just a little graphical bug

**Comment by sandraev** [comment]
I had the same problem, too, with a custom theme, but it wasn't random colors but my wallpaper colors.

**Comment by RedGl0w** [comment]
> I had the same problem, too, with a custom theme, but it wasn't random colors but my wallpaper colors.

These random colors appears after off/on, when the stack is empty
And they are due to a part of a view not being rendered

**Comment by Overengined** [comment]
> These random colors appears after off/on, when the stack is empty
> And they are due to a part of a view not being rendered

Do you think this stack and rendering problem could be related to this issue  ? : https://github.com/Lauryy06/Upsilon/issues/45

**Comment by RedGl0w** [comment]
> Do you think this stack and rendering problem could be related to this issue ? : #45

it's very likely that these issues are totally independant.

**Comment by Lauryy06** [comment]
Now fixed d10d1cd65d4dc0809193554f0b7576db349d2d12.
