### ISSUE TITLE
A dark line on the right side of the screen

### ISSUE THREAD

**Issue by sandraev** [UpsilonNumworks/Upsilon#58]
I've just installed Upsilon 1.22.1 and a dark line appears on the right side of the screen.
I already had this problem on Omega (with 2 lines !).
This is not very important ; it's just aesthetic, but if you can fix it, that would be great.

![bug](https://user-images.githubusercontent.com/92602207/138598761-adcc0bbd-04e8-4a7c-9160-6cca1eb5b5e3.jpg)

**Comment by FaustinM** [comment]
It's not a hardware issue ?

**Comment by sandraev** [comment]
Actually, you may be right. I've been thinking about it.
On all the calculators where I installed Upsilon, there was no such thing.
I'll try to fix that by taking the calculator apart and looking towards the screen. Maybe a false contact? Thank you anyway.
