### ISSUE TITLE
[THEME] theme script.sh doesn't generate reader icon file 

### ISSUE THREAD

**Issue by shaunsingh** [UpsilonNumworks/Upsilon#62]
**Describe the bug**
https://github.com/Lauryy06/Upsilon/blob/upsilon-dev/themes/script.sh script doesn't generate the reader icon file 

**To Reproduce**
1. Edit themeicon json file
2. run `sh script.sh` 
3. run `make OMEGA_USERNAME="<name>" THEME_NAME=<themename> binpack -j8`

**Expected behavior**
The reader icon file should be produced

**Screenshots**
<img width="971" alt="image" src="https://user-images.githubusercontent.com/71196912/139160995-de2c3bbc-d911-4345-b6fe-6c0b63f3ce4c.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/71196912/139161021-8af4f63d-c493-4c76-82b2-2c81739f01ec.png">

**Desktop (please complete the following information):**
 - Omega Version: (upsilon version v15, latest build from my fork)

**Comment by Lauryy06** [comment]
I'm working on it

**Comment by Lauryy06** [comment]
Done in 0a1b3bcaee9a15a3e4c8f1a8e9780ec510f82da4, thanks for the issue !
