### ISSUE TITLE
"Clean" installer

### ISSUE THREAD

**Issue by Overengined** [UpsilonNumworks/Upsilon#68]
It would be very nice if we would be able to install Upsilon from a nice-looking and easy-to-use installer like the one used for Omega. The need for such a thing will grow even bigger as we will try to make Upsilon accessible to more people, since not everyone is ready to use CL based stuff to install an alternative firmware.

**Comment by apoleon33** [comment]
You mean like via a website ?

**Comment by Overengined** [comment]
> You mean like via a website ?

Could be a .exe if needed, the important is the single-click part when you just have to select install and sit back. Of course it would be better if it would be way better if it would be from a website.

**Comment by FaustinM** [comment]
We can do a website, but actually we don't have any design

**Comment by Lauryy06** [comment]
Maybe start with a very basic installer like this one:
![image](https://user-images.githubusercontent.com/80424145/139597712-8966ebc2-8dcd-438e-ad1e-1b71ad1fd8c6.png)
And then add features like a small code editor, a way to manage files on the device, and maybe even merge the website with the Upsilon-External website.
If someone want to do it, here is a library which handle communication with the device : https://github.com/M4xi1m3/numworks.js.

**Comment by shaunsingh** [comment]
Any reason why Upsilon can't just rebrand https://github.com/Omega-Numworks/omega-numworks.github.io? Then just adjust it to get the firmware from GitHub actions

**Comment by Overengined** [comment]
> Any reason why Upsilon can't just rebrand https://github.com/Omega-Numworks/omega-numworks.github.io? Then just adjust it to get the firmware from GitHub actions

It would clearly lack originality

**Comment by shaunsingh** [comment]
No need to be "original", if it works why break it? Omega did lots of good work, take advantage of that. 

After all, Upsilon is the continuation of Omega, not a new project. Continue the website, external apps, etc.

**Comment by apoleon33** [comment]
> No need to be "original", if it works why break it? Omega did lots of good work, take advantage of that. 
> 
> After all, Upsilon is the continuation of Omega, not a new project. Continue the website, external apps, etc. 

I think it would be preferable to do a whole new site, also because it would be clearer for People that "upsilon isn't omega in blue", but  a unique project

**Comment by shaunsingh** [comment]
Its quite literally, omega in blue (+250 commits). Thats not much when you realize omega has 9000 commits over stock upsilon v15

**Comment by Overengined** [comment]
> Its quite literally, omega in blue (+250 commits). Thats not much when you realize omega has 9000 commits over stock upsilon v15

Abslolutely not ! we're using the groundwork done by the Omega community, it's true, but Upsilon is not Omega in blue.

**Comment by apoleon33** [comment]
> Its quite literally, omega in blue (+250 commits). Thats not much when you realize omega has 9000 commits over stock upsilon v15

Bruh upsilon is litteraly 3 month old  ._.

**Comment by shaunsingh** [comment]
Not sure how age plays into this. Regardless of how those commits were done, the fact is those commits are built on omega. Plus, Upsilon maintains its own forks of the RPN/Atomic/External repos, forking the website would continue that trend

**Comment by Overengined** [comment]
I think that we can close this issue now ?

**Comment by Yaya-Cout** [comment]
I think of the link of the installer should be added into the README before

**Comment by Overengined** [comment]
I agree

**Comment by Lauryy06** [comment]
Yes, I forgot it. If anyone here is looking for the website, it is [here](https://lolocomotive.github.io/Upsilon-website/).
