### ISSUE TITLE
Issues with submodules: Direct fetching of that commit failed.

### ISSUE THREAD

**Issue by shaunsingh** [UpsilonNumworks/Upsilon#72]
**Describe the bug**
`git submodule update` fails with the following output: 
```zsh
~/I/Upsilon (upsilon-dev ✓) λ git submodule update
Cloning into '/Users/shauryasingh/IdeaProjects/Upsilon/apps/atomic'...
Cloning into '/Users/shauryasingh/IdeaProjects/Upsilon/apps/rpn'...
Submodule path 'apps/atomic': checked out '69f7a06ba53eaae9ba2ab8f0c0318e2f77455f4d'
fatal: remote error: upload-pack: not our ref b51172c32fdfb5a36c7526799965d6f3da613d69
Fetched in submodule path 'apps/rpn', but it did not contain b51172c32fdfb5a36c7526799965d6f3da613d69. Direct fetching of that commit failed.
```

This is because you updated the submodules to use your forks (https://github.com/Lauryy06/Upsilon/commit/84d88a3e8d50a9f8665117fad7372008416f5066) but you didn't update the commits they were pinned to 
<img width="179" alt="image" src="https://user-images.githubusercontent.com/71196912/139899536-52941ac6-0877-4ef4-a308-6c8e10eb9217.png">

I recommend you update those pins to match the latest commit on each repo

As expected, the commit before that (https://github.com/Lauryy06/Upsilon/commit/00b5d4b9fe58c7a018e9b31ae74a189bf464a23e) clones and builds just fine

**To Reproduce**
1. Clone repo
2. error should popup if you use the `--recursive` flag

**Expected behavior**
Upsilon should download/build as expected 

**Screenshots**

**Desktop (please complete the following information):**
 - Upsilon Version: [go to settings > about > Upsilon Version and type the version here]

**Comment by Lauryy06** [comment]
Thanks for the issue, I fixed it by pushing my changes on the RPN repository.
