### ISSUE TITLE
[Themes] upsilon_light / upsilon_dark themes do not contain reader icon

### ISSUE THREAD

**Issue by shaunsingh** [UpsilonNumworks/Upsilon#74]
Both the upsilon light/dark themes do not contain a reader icon, and fall back the red omega one. It would be nice to use the themes script to generate a new icon.

**Comment by Yaya-Cout** [comment]
I think of this issue can be closed because of 0a1b3bcaee9a15a3e4c8f1a8e9780ec510f82da4 add the reader icon

**Comment by Lauryy06** [comment]
Only to the upsilon light theme
