### ISSUE TITLE
Executing a (specific) python script cause a reset of the calculator

### ISSUE THREAD

**Issue by fime-space** [UpsilonNumworks/Upsilon#79]
**Describe the bug**
When I launch [this script](https://my.numworks.com/python/fime/ruin) the title of the game appear but when i press OK to continue the game execution (and load the level, which is object-oriented, so it probably takes a lot of memory) the calculator just reset ...

**To Reproduce**
1. Go to https://my.numworks.com/python/fime/ruin and download the script
2. Run it
3. Press OK on the title screen

**Expected behavior**
The calculator should reset with a short black screen time

**Desktop (please complete the following information):**
 - Upsilon Version: 1.22.1
 - I use some external apps (nofrendo with roms and khiCAS)
 - I have a custom wallpaper

**Edit**

This appened with really simpler scripts, even the cause is not necessarly the same.

**Comment by Lauryy06** [comment]
Hi, thanks for reporting the outcome. However the game runs perfectly on my n0110 (it's a piece of art btw). Can you click on "Epsilon version" and tell me on which commit your version is based? Personally I am in #84d88a3

**Comment by RedGl0w** [comment]
And even better dump your internal and external flash ?

**Comment by fime-space** [comment]
> And even better dump your internal and external flash ?

Hi RedGl0w, how could i do it ?

**Comment by RedGl0w** [comment]
> Hi RedGl0w, how could i do it ?

https://ti-planet.github.io/webdfu_numworks/n0110/

**Comment by fime-space** [comment]
Hi, as github doesn't support .bin files upload, I send it to you via Discord:

[Internal](https://cdn.discordapp.com/attachments/830778829840449567/909092617747300352/internal.bin)
[External](https://cdn.discordapp.com/attachments/830778829840449567/909092623829069824/external.bin)

**Comment by Yaya-Cout** [comment]
I don't have bugs with this script.

**Comment by Lauryy06** [comment]
Yes, if the bug is not reproducible I will close the issue soon.

**Comment by fime-space** [comment]
okay, maybe that was due to my external

**Comment by Lauryy06** [comment]
I don't think so, but in my opinion it's just that the bug is not related to the script.
