### ISSUE TITLE
Add extremum in aditionnal quatradic polynomial informations

### ISSUE THREAD

**Issue by Zaitara** [UpsilonNumworks/Upsilon#92]
**Is your feature request related to a problem? Please describe.**
When going into a quadratic polynomial advanced informations, a lot of useful data are shown : factorised and canonical forms, delta, x1 and x2 if available, but not the extremum of the function : `-b/2a`. 

**Describe the solution you'd like**
It would be great to also add the extremum of the function, `-b/2a`, in this menu. It would also be interesting to name it minimum/maximum (minimum if a > 0). Internally, it is named alpha, so it's not really hard to implement. 

**Additional context**
N/A

**Comment by Lauryy06** [comment]
Thanks for the question, but you probably know that the informations about extremum are given by the canonical form. I chose not to add the theme to the menu so as not to overload it.

So I intentionnaly won't fix your issue, sorry. (but thanks for it !)
